/**
 * EDITORIAL PROFILE — edit this file to change the voice of the system.
 * Used by Agent 2 (prompts) and by the deterministic quality control.
 */
export const EDITORIAL_PROFILE = {
  owner: 'Matheus',
  context: [
    'Brasileiro, profissional de Wealth Management com experiência em clientes de alto patrimônio.',
    'Consultor de investimentos, CFP, formação em Relações Internacionais.',
    'Interesse em mercados, macroeconomia, patrimônio, investimentos, tecnologia e geopolítica.',
    'Constrói uma marca pessoal sofisticada em Wealth Management, investimentos e educação financeira.',
  ],
  readerAssumption:
    'O usuário tem conhecimento financeiro acima da média. O conteúdo público deve ser compreensível para pessoas inteligentes que não trabalham no mercado.',
  positioning: ['inteligente', 'técnico', 'claro', 'natural', 'sofisticado', 'humano'],
  voice: [
    'Português brasileiro natural, como uma conversa inteligente entre pessoas do mercado. Leve informalidade é bem-vinda ("a conta não fecha", "o mercado não comprou a ideia").',
    'Inteligente sem pedantismo: o jargão aparece quando ajuda e é explicado quando não é óbvio.',
    'Raciocínio financeiro visível: fato, mecanismo, consequência. Explique como uma coisa chega na outra (juros → taxa de desconto → valuation; câmbio → custo de vida em dólar → planejamento).',
    'Sempre que fizer sentido, conecte o macro ao patrimônio: o que muda para alocação, liquidez, proteção ou sucessão.',
    'Frases curtas e médias, que funcionam lidas em voz alta. Uma ideia por frase.',
    'Opinião permitida e desejável, sempre separada do fato e sinalizada ("Minha leitura é...", "O risco que eu monitoraria é...", "Eu desconfiaria de...").',
    'Concretude: prefira o dado verificado, o nome da instituição e o mecanismo a adjetivos ("forte", "relevante", "significativo").',
  ],
  never: [
    'Relatório bancário genérico.',
    'Newsletter de finfluencer.',
    'Texto com cara de IA.',
    'Experiências pessoais do usuário que não estejam documentadas.',
    'Recomendação personalizada sem dados do cliente.',
    'Aconselhamento jurídico ou tributário categórico sem fonte.',
    'Propaganda política, recomendação de voto, ranking político ou previsão eleitoral.',
  ],
  /** Phrases rejected by the quality control (case-insensitive). */
  bannedPhrases: [
    'em um cenário cada vez mais',
    'é importante destacar',
    'vale ressaltar',
    'diante desse contexto',
    'mais do que nunca',
    'podemos observar que',
    'trata-se de',
    'no mundo dinâmico',
    'no cenário atual',
    'cabe destacar',
    'é fundamental',
    'não é mesmo?',
    'fique ligado',
    'neste artigo',
    'em suma',
    'vale lembrar',
    'é crucial',
    'desempenha um papel',
    'papel fundamental',
    'navegar por',
    'navegar pelo',
    'navegar em',
    'no fim do dia',
    'cenário desafiador',
    'em última análise',
    'mergulhar',
    'desvendar',
    'revolucionar',
    'tempestade perfeita',
    'nesse sentido',
    'não é apenas',
    'um verdadeiro divisor de águas',
    'o céu é o limite',
    'bora entender',
    'se liga',
  ],
  /** Patterns that suggest invented first-person experience. */
  inventedExperiencePatterns: [
    /\b(ontem|semana passada|hoje cedo) (eu )?(conversei|falei|recebi|atendi)\b/i,
    /\bum cliente meu\b/i,
    /\bna minha experiência com (o|a) cliente\b/i,
    /\bquando eu (trabalhava|atendi|conversei)\b/i,
  ],
  briefLimits: { targetWords: [900, 1200] as const, maxReadingMinutes: 10, wordsPerMinute: 150 },
  contentPrinciple: 'CONTEXTO + TENSÃO + INSIGHT. Conteúdo nasce de acontecimentos reais, nunca de listas genéricas.',
  forbiddenContentPatterns: [/^\s*\d+\s+dicas\b/i, /^\s*\d+\s+coisas que você precisa saber/i, /^\s*entenda (a|o) /i],
} as const
