import type { SourceDefinition } from '../src/core/schemas'

/**
 * SOURCE REGISTRY
 *
 * Every source the system may use, with its authority level and priority.
 * To add, disable or reprioritise a source, edit this file (docs/market-intelligence.md).
 *
 * Rules enforced by code:
 *  - official sources are the authority for macro numbers;
 *  - market data is VERIFIED by two agreeing sources on the same reference date, or by
 *    the instrument's official publisher alone (official_single, e.g. Treasury, PTAX, B3);
 *  - `lineage` groups sources that share the same underlying feed: agreement between two
 *    sources of the same lineage is never called "independent";
 *  - `unofficial_vendor` sources (Yahoo) never count toward VERIFIED;
 *  - sources marked `not_integrated` are never fetched automatically.
 */
export const SOURCES: SourceDefinition[] = [
  /* ---------------------------- MARKET ---------------------------- */
  {
    id: 'investing',
    name: 'Investing.com',
    kind: 'market',
    authority: 'data_vendor',
    priority: 0,
    homepage: 'https://www.investing.com',
    access: 'manual',
    enabled: false,
    regions: ['GLOBAL'],
    limitation:
      'Referência de mercado para validação e pesquisa MANUAL. Sem API pública oficial, os Termos de Uso proíbem coleta automatizada e as páginas retornam HTTP 403 (anti-bot), confirmado em 29/09/2026. ' +
      'Não há crawler e não há tentativa de contornar bloqueios. Todo dado automático usa fontes estruturadas e é marcado com source_fallback = true.',
  },
  {
    id: 'brapi',
    lineage: 'b3',
    name: 'brapi.dev (B3)',
    kind: 'market',
    authority: 'data_vendor',
    priority: 1,
    homepage: 'https://brapi.dev',
    access: 'api',
    enabled: true,
    credentialEnv: 'BRAPI_TOKEN',
    regions: ['BR'],
    limitation:
      'Fonte prioritária para o Brasil. Auditado em 30/09/2026 com a conta conectada (plano Gratuito): Ibovespa (^BVSP) cotação e histórico diário OK, com atraso de até 30 min e 1 requisição simultânea. ' +
      'Câmbio (/v2/currency, que segundo a BRAPI deriva da PTAX do BCB), cripto e Selic/inflação exigem o plano Startup (pago), por isso NÃO são usados. A PTAX é lida direto do BCB (fonte original). ' +
      'A API REST exige BRAPI_TOKEN mesmo no plano gratuito (^BVSP sem token → 401). Em sessões do Claude, o conector MCP da BRAPI pode alimentar o Agent 1 via `mi morning --observations`.',
  },
  {
    id: 'bitstamp',
    lineage: 'bitstamp',
    name: 'Bitstamp',
    kind: 'market',
    authority: 'exchange',
    priority: 3,
    homepage: 'https://www.bitstamp.net',
    access: 'api',
    enabled: true,
    regions: ['GLOBAL'],
    limitation: 'API pública documentada, sem chave (validada em 30/09/2026).',
  },
  {
    id: 'gemini',
    lineage: 'gemini',
    name: 'Gemini',
    kind: 'market',
    authority: 'exchange',
    priority: 4,
    homepage: 'https://www.gemini.com',
    access: 'api',
    enabled: true,
    regions: ['GLOBAL'],
    limitation: 'API pública documentada, sem chave (validada em 30/09/2026).',
  },
  {
    id: 'bok-ecos',
    lineage: 'krx',
    name: 'Bank of Korea — ECOS',
    kind: 'market',
    authority: 'official',
    priority: 1,
    homepage: 'https://ecos.bok.or.kr',
    access: 'api',
    enabled: true,
    credentialEnv: 'BOK_ECOS_KEY',
    regions: ['ASIA'],
    limitation: 'Banco central da Coreia, série 802Y001/0001000 (KOSPI, fechamento diário). Sem BOK_ECOS_KEY, usa a chave pública de exemplo ("sample"), que o BOK oferece para testes e tem limite de linhas. Para produção, cadastre uma chave gratuita.',
  },
  {
    id: 'stooq',
    lineage: 'stooq',
    name: 'Stooq',
    kind: 'market',
    authority: 'data_vendor',
    priority: 2,
    homepage: 'https://stooq.com',
    access: 'csv',
    enabled: true,
    regions: ['GLOBAL'],
    limitation: 'Download CSV público de cotações, sem SLA. VALIDADO EM 29/09/2026: responde HTTP 403 a IPs de datacenter (Vercel). Mantido como tentativa, mas índices de Europa e Ásia e o DXY exigem TWELVEDATA_API_KEY ou outro fornecedor licenciado para serem verificados.',
  },
  {
    id: 'fred',
    lineage: 'fred',
    name: 'FRED — Federal Reserve Bank of St. Louis',
    kind: 'market',
    authority: 'official',
    priority: 3,
    homepage: 'https://fred.stlouisfed.org',
    access: 'api',
    enabled: true,
    credentialEnv: 'FRED_API_KEY',
    regions: ['US', 'GLOBAL'],
    limitation: 'Séries diárias publicadas com 1 dia útil de defasagem. Sem chave, usa o download CSV público (fredgraph).',
  },
  {
    id: 'us-treasury',
    lineage: 'us-treasury',
    name: 'U.S. Department of the Treasury',
    kind: 'market',
    authority: 'official',
    priority: 1,
    homepage: 'https://home.treasury.gov',
    access: 'csv',
    enabled: true,
    regions: ['US'],
  },
  {
    id: 'bcb-ptax',
    lineage: 'bcb',
    name: 'Banco Central do Brasil — PTAX (SGS)',
    kind: 'market',
    authority: 'official',
    priority: 1,
    homepage: 'https://www.bcb.gov.br',
    access: 'api',
    enabled: true,
    regions: ['BR'],
    limitation: 'PTAX é uma taxa de referência (fixing) calculada ao longo do dia, não o spot de fechamento. Usada como âncora oficial com tolerância de validação maior.',
  },
  {
    id: 'coingecko',
    lineage: 'coingecko',
    name: 'CoinGecko',
    kind: 'market',
    authority: 'data_vendor',
    priority: 1,
    homepage: 'https://www.coingecko.com',
    access: 'api',
    enabled: true,
    credentialEnv: 'COINGECKO_DEMO_KEY',
    regions: ['GLOBAL'],
    limitation: 'Sem chave, responde HTTP 403 a IPs de datacenter (revalidado em 30/09/2026). Configure COINGECKO_DEMO_KEY (gratuita). BTC é verificado por Coinbase, Kraken, Bitstamp e Gemini.',
  },
  {
    id: 'ecb-fx',
    lineage: 'ecb',
    name: 'European Central Bank — taxas de referência',
    kind: 'market',
    authority: 'official',
    priority: 2,
    homepage: 'https://data.ecb.europa.eu/data/datasets/EXR',
    access: 'api',
    enabled: true,
    regions: ['EU', 'BR'],
    limitation: 'Taxas de referência diárias (≈14:15 CET). USD/BRL é derivado deterministicamente como EUR/BRL ÷ EUR/USD, como validação cruzada da PTAX. O DXY é calculado pela fórmula pública da ICE (EUR, JPY, GBP, CAD, SEK, CHF) sobre os fixings do ECB: é uma aproximação, não o índice oficial da ICE.',
  },
  {
    id: 'coinbase',
    lineage: 'coinbase',
    name: 'Coinbase',
    kind: 'market',
    authority: 'exchange',
    priority: 2,
    homepage: 'https://www.coinbase.com',
    access: 'api',
    enabled: true,
    regions: ['GLOBAL'],
  },
  {
    id: 'kraken',
    lineage: 'kraken',
    name: 'Kraken',
    kind: 'market',
    authority: 'exchange',
    priority: 3,
    homepage: 'https://www.kraken.com',
    access: 'api',
    enabled: true,
    regions: ['GLOBAL'],
  },
  {
    id: 'twelvedata',
    lineage: 'twelvedata',
    name: 'Twelve Data',
    kind: 'market',
    authority: 'data_vendor',
    priority: 4,
    homepage: 'https://twelvedata.com',
    access: 'api',
    enabled: true,
    credentialEnv: 'TWELVEDATA_API_KEY',
    regions: ['GLOBAL'],
    limitation:
      'Fornecedor unificado preferido (bakeoff 30/09/2026). Opcional, gratuita com chave (cadastro); a chave "demo" responde 401 para cotações. Símbolos descobertos nas listas de referência (/indices, /forex_pairs, /cryptocurrencies): BVSP, STOXX50E, GDAXI, FTSE, N225, HSI, 000001, KOSPI, USD/BRL, EUR/BRL, BTC/USD. ' +
      'S&P 500, Nasdaq Composite, Dow Jones e DXY não constam do catálogo de índices. Cotações não testadas por falta de chave (TWELVEDATA_API_KEY ausente).',
  },
  {
    id: 'fmp',
    lineage: 'fmp',
    name: 'Financial Modeling Prep',
    kind: 'market',
    authority: 'data_vendor',
    priority: 4,
    homepage: 'https://site.financialmodelingprep.com/developer/docs',
    access: 'api',
    enabled: true,
    credentialEnv: 'FMP_API_KEY',
    regions: ['US', 'GLOBAL'],
    limitation: 'Opcional, com chave. Candidato para S&P 500, Nasdaq Composite, Dow Jones e DXY (fora do catálogo da Twelve Data). Não testado no bakeoff: FMP_API_KEY ausente. Cobertura de índices no plano gratuito não confirmada.',
  },

  /* ----------------------------- MACRO ---------------------------- */
  {
    id: 'b3-arquivos',
    lineage: 'b3',
    name: 'B3 — Arquivos Públicos (TradeInformationConsolidated)',
    kind: 'market',
    authority: 'official',
    priority: 1,
    homepage: 'https://arquivos.b3.com.br/',
    access: 'csv',
    enabled: true,
    regions: ['BR'],
    limitation:
      'Arquivo oficial e público da B3 (download em duas etapas no portal de Arquivos Públicos). Usado para a curva DI1: contratos reais com a taxa de ajuste (AdjstdQtTax) do pregão. ~5 MB por arquivo; 2 downloads por dia (D e D-1). ' +
      'O fluxo de download é o mesmo usado pelo portal público, sem login; não é uma API documentada formalmente, por isso está registrado como decisão a revisar.',
  },
  {
    id: 'yahoo',
    lineage: 'yahoo',
    name: 'Yahoo Finance (endpoint JSON de gráfico)',
    kind: 'market',
    authority: 'unofficial_vendor',
    priority: 9,
    homepage: 'https://finance.yahoo.com',
    access: 'api',
    enabled: false,
    regions: ['GLOBAL'],
    limitation:
      'Prova de conceito técnica (bakeoff de 30/09/2026: 15/15 ativos). Endpoint não documentado oficialmente e com termos de uso restritivos: nunca é fonte primária institucional nem conta para VERIFIED (verification_method = unofficial_vendor). ' +
      'Fonte de exibição (nunca conta para VERIFIED): fechamento mais recente no modo automático e cotação corrente no manual. Ligado por padrão; MI_ENABLE_YAHOO_FALLBACK=false desliga fora do modo manual.',
  },
  {
    id: 'bcb-sgs',
    name: 'Banco Central do Brasil — SGS',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://www3.bcb.gov.br/sgspub',
    access: 'api',
    enabled: true,
    regions: ['BR'],
  },
  {
    id: 'bcb-focus',
    name: 'Banco Central do Brasil — Focus (Expectativas)',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://www.bcb.gov.br/publicacoes/focus',
    access: 'api',
    enabled: true,
    regions: ['BR'],
  },
  {
    id: 'ibge-sidra',
    name: 'IBGE — SIDRA',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://sidra.ibge.gov.br',
    access: 'api',
    enabled: true,
    regions: ['BR'],
  },
  {
    id: 'bls',
    name: 'U.S. Bureau of Labor Statistics',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://www.bls.gov',
    access: 'api',
    enabled: true,
    regions: ['US'],
    limitation: 'API v1 sem chave: limite diário baixo de requisições. Consultas agrupadas por execução.',
  },
  {
    id: 'fred-macro',
    name: 'FRED — Federal Reserve Bank of St. Louis',
    kind: 'macro',
    authority: 'official',
    priority: 2,
    homepage: 'https://fred.stlouisfed.org',
    access: 'api',
    enabled: true,
    credentialEnv: 'FRED_API_KEY',
    regions: ['US', 'CN', 'GLOBAL'],
    limitation: 'Republica dados de BEA, BLS, Fed e OECD. É usada como validação secundária ou como fonte oficial do Fed.',
  },
  {
    id: 'ecb',
    name: 'European Central Bank — Data Portal',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://data.ecb.europa.eu',
    access: 'api',
    enabled: true,
    regions: ['EU'],
  },
  {
    id: 'nbs-china',
    name: 'National Bureau of Statistics of China',
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'https://www.stats.gov.cn/english/',
    access: 'not_integrated',
    enabled: false,
    regions: ['CN'],
    limitation: 'Sem API estruturada estável e acessível. Dados da China entram por importação manual com URL da fonte, ou como UNAVAILABLE.',
  },
  {
    id: 'pboc',
    name: "People's Bank of China",
    kind: 'macro',
    authority: 'official',
    priority: 1,
    homepage: 'http://www.pbc.gov.cn/en/',
    access: 'not_integrated',
    enabled: false,
    regions: ['CN'],
    limitation: 'Sem API estruturada. Decisões de LPR e RRR entram por importação manual com URL oficial.',
  },

  /* ----------------------------- NEWS ----------------------------- */
  { id: 'rss-bbc-business', name: 'BBC News — Business', kind: 'news', authority: 'press', priority: 1, homepage: 'https://www.bbc.com/news/business', access: 'rss', enabled: true, regions: ['GLOBAL'] },
  { id: 'rss-g1-economia', name: 'g1 Economia', kind: 'news', authority: 'press', priority: 1, homepage: 'https://g1.globo.com/economia/', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-infomoney', name: 'InfoMoney', kind: 'news', authority: 'press', priority: 1, homepage: 'https://www.infomoney.com.br', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-cnnbrasil-economia', name: 'CNN Brasil', kind: 'news', authority: 'press', priority: 1, homepage: 'https://www.cnnbrasil.com.br/economia/', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-exame', name: 'Exame', kind: 'news', authority: 'press', priority: 2, homepage: 'https://exame.com', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-cnbc-markets', name: 'CNBC — Markets', kind: 'news', authority: 'press', priority: 2, homepage: 'https://www.cnbc.com/markets/', access: 'rss', enabled: true, regions: ['US'] },
  { id: 'rss-fed-press', name: 'Federal Reserve — Press Releases', kind: 'news', authority: 'official', priority: 1, homepage: 'https://www.federalreserve.gov/newsevents/pressreleases.htm', access: 'rss', enabled: true, regions: ['US'] },
  { id: 'rss-ecb-press', name: 'ECB — Press', kind: 'news', authority: 'official', priority: 1, homepage: 'https://www.ecb.europa.eu/press/html/index.en.html', access: 'rss', enabled: true, regions: ['EU'] },
  {
    id: 'reuters',
    name: 'Reuters',
    kind: 'news',
    authority: 'press',
    priority: 1,
    homepage: 'https://www.reuters.com',
    access: 'not_integrated',
    enabled: false,
    regions: ['GLOBAL'],
    limitation: 'Descontinuou os feeds RSS públicos. O acesso estruturado exige licença (Reuters Connect).',
  },
  {
    id: 'ap',
    name: 'Associated Press',
    kind: 'news',
    authority: 'press',
    priority: 1,
    homepage: 'https://apnews.com',
    access: 'not_integrated',
    enabled: false,
    regions: ['GLOBAL'],
    limitation: 'Sem feed RSS público oficial. O acesso estruturado exige licença (AP Media API).',
  },
  { id: 'rss-valor', name: 'Valor Econômico', kind: 'news', authority: 'press', priority: 1, homepage: 'https://valor.globo.com', access: 'rss', enabled: true, regions: ['BR'], limitation: 'Feed público com manchetes; conteúdo completo sob paywall (usamos apenas título e resumo curto).' },
  { id: 'rss-estadao-economia', name: 'Estadão — Economia', kind: 'news', authority: 'press', priority: 1, homepage: 'https://www.estadao.com.br/economia/', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-bcb-notas', name: 'Banco Central do Brasil — Notas à imprensa', kind: 'news', authority: 'official', priority: 1, homepage: 'https://www.bcb.gov.br/detalhenoticia', access: 'rss', enabled: true, regions: ['BR'] },
  { id: 'rss-marketwatch', name: 'MarketWatch — Top Stories', kind: 'news', authority: 'press', priority: 2, homepage: 'https://www.marketwatch.com', access: 'rss', enabled: true, regions: ['US'] },
  { id: 'rss-ft-markets', name: 'Financial Times — Markets', kind: 'news', authority: 'press', priority: 2, homepage: 'https://www.ft.com/markets', access: 'rss', enabled: true, regions: ['GLOBAL'] },
  { id: 'rss-nyt-business', name: 'The New York Times — Business', kind: 'news', authority: 'press', priority: 2, homepage: 'https://www.nytimes.com/section/business', access: 'rss', enabled: true, regions: ['US'] },

  /* --------------------------- CALENDAR --------------------------- */
  { id: 'cal-official-seed', name: 'Calendários oficiais (BCB, Fed, ECB, IBGE, BLS)', kind: 'calendar', authority: 'official', priority: 1, homepage: 'https://www.bcb.gov.br/controleinflacao/calendarioreunioescopom', access: 'manual', enabled: true, regions: ['GLOBAL'] },
  { id: 'ibge-calendario', name: 'IBGE — Calendário de divulgações', kind: 'calendar', authority: 'official', priority: 1, homepage: 'https://www.ibge.gov.br/calendario-de-divulgacoes.html', access: 'api', enabled: true, regions: ['BR'] },
  { id: 'cal-computed-holidays', name: 'Feriados nacionais (Lei 662/1949 e Lei 6.802/1980, calculados)', kind: 'calendar', authority: 'official', priority: 2, homepage: 'https://www.planalto.gov.br/ccivil_03/leis/l0662.htm', access: 'manual', enabled: true, regions: ['BR'] },
]

/** Public RSS endpoints. Validated at runtime; failures are logged in agent_runs, never fatal. */
export const RSS_FEEDS: Record<string, string> = {
  'rss-bbc-business': 'https://feeds.bbci.co.uk/news/business/rss.xml',
  'rss-g1-economia': 'https://g1.globo.com/rss/g1/economia/',
  'rss-infomoney': 'https://www.infomoney.com.br/feed/',
  'rss-cnnbrasil-economia': 'https://www.cnnbrasil.com.br/feed/',
  'rss-valor': 'https://valor.globo.com/rss/valor',
  'rss-estadao-economia': 'https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/economia/',
  'rss-bcb-notas': 'https://www.bcb.gov.br/api/feed/sitebcb/sitefeeds/notasImprensa',
  'rss-marketwatch': 'https://feeds.content.dowjones.io/public/rss/mw_topstories',
  'rss-ft-markets': 'https://www.ft.com/markets?format=rss',
  'rss-nyt-business': 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
  'rss-exame': 'https://exame.com/feed/',
  'rss-cnbc-markets': 'https://www.cnbc.com/id/15839069/device/rss/rss.html',
  'rss-fed-press': 'https://www.federalreserve.gov/feeds/press_all.xml',
  'rss-ecb-press': 'https://www.ecb.europa.eu/rss/press.html',
}

export function getSource(id: string): SourceDefinition {
  const s = SOURCES.find((x) => x.id === id)
  if (!s) throw new Error(`Unknown source "${id}"`)
  return s
}

export function sourceName(id: string | null | undefined): string {
  if (!id) return '—'
  return SOURCES.find((x) => x.id === id)?.name ?? id
}
