'use client'
import {useState} from 'react'
import {createClient} from '@/lib/supabase/client'
export default function ClientProfileActions({clientId,initialStatus}:{clientId:string;initialStatus:string}){
 const [edit,setEdit]=useState(false),[family,setFamily]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[status,setStatus]=useState(initialStatus)
 const [form,setForm]=useState({full_name:'',email:'',phone:'',cpf_cnpj:'',birth_date:'',postal_code:'',address:'',neighborhood:'',city:'',state:''})
 const [fam,setFam]=useState({full_name:'',relationship:'Cônjuge',email:'',phone:'',cpf:''})
 const load=async()=>{const {data}=await createClient().from('clients').select('full_name,email,phone,cpf_cnpj,birth_date,postal_code,address,neighborhood,city,state').eq('id',clientId).single();if(data)setForm({...data,full_name:data.full_name||'',email:data.email||'',phone:data.phone||'',cpf_cnpj:data.cpf_cnpj||'',birth_date:data.birth_date||'',postal_code:data.postal_code||'',address:data.address||'',neighborhood:data.neighborhood||'',city:data.city||'',state:data.state||''})}
 const save=async()=>{setSaving(true);setMsg('');const {error}=await createClient().from('clients').update(form).eq('id',clientId);if(error)setMsg(error.message);else{setEdit(false);location.reload()}setSaving(false)}
 const addFamily=async()=>{setSaving(true);setMsg('');const s=createClient(),{data:a}=await s.auth.getUser();if(!a.user){setMsg('Sessão expirada.');setSaving(false);return}const {data:u}=await s.from('users').select('tenant_id').eq('id',a.user.id).single();const {error}=await s.from('client_family_members').insert({tenant_id:u?.tenant_id,client_id:clientId,...fam});if(error)setMsg(error.message);else{setFamily(false);location.reload()}setSaving(false)}
 const send=async()=>{setSaving(true);const {error}=await createClient().from('clients').update({contract_status:'awaiting_signature'}).eq('id',clientId);if(error)setMsg(error.message);else{setStatus('awaiting_signature');setMsg('Cliente marcado como aguardando assinatura. A integração com o provedor será conectada ao modelo em Configurações.')}setSaving(false)}
 return <div className="profile-actions"><button className="secondary-btn" onClick={()=>{load();setEdit(true)}}>Editar cadastro</button><button className="secondary-btn" onClick={()=>setFamily(true)}>＋ Família</button>{status==='pending'&&<button className="primary-btn" disabled={saving} onClick={send}>Enviar contrato para assinatura</button>}{msg&&<span className="profile-action-message">{msg}</span>}
 {edit&&<div className="modal-backdrop"><div className="modal dashboard-modal"><div className="modal-head"><div><p className="eyebrow">Cadastro</p><h2>Editar cliente</h2></div><button className="icon-btn" onClick={()=>setEdit(false)}>×</button></div><div className="form-grid">{Object.entries(form).map(([k,v])=><label key={k}>{k.replace('_',' ')}<input type={k==='birth_date'?'date':'text'} value={v||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setEdit(false)}>Cancelar</button><button className="primary-btn" disabled={saving} onClick={save}>{saving?'Salvando...':'Salvar'}</button></div></div></div>}
 {family&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">Estrutura familiar</p><h2>Adicionar membro</h2></div><button className="icon-btn" onClick={()=>setFamily(false)}>×</button></div><div className="form-grid"><label className="full">Nome<input value={fam.full_name} onChange={e=>setFam({...fam,full_name:e.target.value})}/></label><label>Relação<select value={fam.relationship} onChange={e=>setFam({...fam,relationship:e.target.value})}><option>Cônjuge</option><option>Filho(a)</option><option>Pai/Mãe</option><option>Outro</option></select></label><label>CPF<input value={fam.cpf} onChange={e=>setFam({...fam,cpf:e.target.value})}/></label><label>E-mail<input value={fam.email} onChange={e=>setFam({...fam,email:e.target.value})}/></label><label>Telefone<input value={fam.phone} onChange={e=>setFam({...fam,phone:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setFamily(false)}>Cancelar</button><button className="primary-btn" disabled={!fam.full_name||saving} onClick={addFamily}>{saving?'Salvando...':'Adicionar'}</button></div></div></div>}
 </div>
}
