'use client'
import {useState} from 'react'
import {createClient} from '@/lib/supabase/client'
type Tx={id:string;transaction_date:string;description_original:string;amount:number;direction:string;category_id:string|null;account_id:string|null}
type Cat={id:string;name:string;icon?:string|null}
type Account={id:string;institution_id:string|null;account_type:string;masked_identifier:string|null}
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const parse=(v:string)=>v.includes(',')?Number(v.replace(/\./g,'').replace(',','.')):Number(v)
export default function ClientTransactions({clientId,rows,categories,accounts}:{clientId:string;rows:Tx[];categories:Cat[];accounts:Account[]}){
 const [items,setItems]=useState(rows),[selected,setSelected]=useState<string[]>([]),[menu,setMenu]=useState<string|null>(null),[edit,setEdit]=useState<Tx|null>(null),[category,setCategory]=useState<Tx|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const [form,setForm]=useState({date:'',description:'',amount:'',direction:'debit',account_id:'',category_id:''});const all=items.length>0&&items.every(x=>selected.includes(x.id))
 function openEdit(t:Tx){setEdit(t);setMenu(null);setMessage('');setForm({date:t.transaction_date,description:t.description_original,amount:String(t.amount),direction:t.direction,account_id:t.account_id||'',category_id:t.category_id||''})}
 async function saveEdit(){if(!edit)return;setSaving(true);setMessage('');try{const {error}=await createClient().from('transactions').update({transaction_date:form.date,description_original:form.description,description_normalized:form.description.trim().toLowerCase(),amount:parse(form.amount),direction:form.direction,account_id:form.account_id||null,category_id:form.category_id||null,classification_source:'manual',user_confirmed:true}).eq('id',edit.id);if(error)throw Error(error.message);setItems(p=>p.map(t=>t.id===edit.id?{...t,transaction_date:form.date,description_original:form.description,amount:parse(form.amount),direction:form.direction,account_id:form.account_id||null,category_id:form.category_id||null}:t));setEdit(null)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível editar a movimentação.')}finally{setSaving(false)}}
 async function remove(ids:string[]){if(!ids.length)return;setSaving(true);setMessage('');try{const {error}=await createClient().from('transactions').update({is_active:false,deleted_at:new Date().toISOString()}).in('id',ids);if(error)throw Error(error.message);setItems(p=>p.filter(t=>!ids.includes(t.id)));setSelected(p=>p.filter(id=>!ids.includes(id)));setMenu(null)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível excluir a movimentação.')}finally{setSaving(false)}}
 async function saveCategory(){if(!category)return;setSaving(true);setMessage('');try{const {error}=await createClient().from('transactions').update({category_id:form.category_id||null,classification_source:'manual',user_confirmed:true}).eq('id',category.id);if(error)throw Error(error.message);setItems(p=>p.map(t=>t.id===category.id?{...t,category_id:form.category_id||null}:t));setCategory(null)}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível alterar a categoria.')}finally{setSaving(false)}}
 const cat=(id:string|null)=>categories.find(c=>c.id===id)?.name||'Não categorizado';const ref=(id:string|null)=>accounts.find(a=>a.id===id)?.institution_id||'—'
 return <div className="transaction-manager"><div className="table-wrap"><table><thead><tr><th className="check-col"><input type="checkbox" checked={all} onChange={e=>setSelected(e.target.checked?items.map(t=>t.id):[])}/></th><th>Categoria</th><th>Data</th><th>Descrição</th><th>Valor</th><th>Referência</th><th></th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(p=>e.target.checked?[...p,t.id]:p.filter(id=>id!==t.id))}/></td><td><button className="category-link" onClick={()=>{setCategory(t);setForm(f=>({...f,category_id:t.category_id||''}))}}><span className="category-mini">{categories.find(c=>c.id===t.category_id)?.icon||'◌'}</span>{cat(t.category_id)}</button></td><td>{new Date(t.transaction_date).toLocaleDateString('pt-BR')}</td><td><strong>{t.description_original}</strong></td><td className={t.direction==='credit'?'positive':'negative'}>{t.direction==='credit'?'+':'-'}{brl.format(Number(t.amount))}</td><td>{ref(t.account_id)}</td><td className="menu-cell"><button className="dots-btn" onClick={()=>setMenu(menu===t.id?null:t.id)}>⋮</button>{menu===t.id&&<div className="row-menu"><button onClick={()=>openEdit(t)}>Editar</button><button className="danger-text" onClick={()=>remove([t.id])}>Excluir</button></div>}</td></tr>)}{!items.length&&<tr><td colSpan={7} className="table-empty">Nenhuma movimentação encontrada.</td></tr>}</tbody></table></div>{selected.length>0&&<div className="bulk-bar"><span><strong>{selected.length}</strong> selecionada(s)</span><button className="secondary-btn danger-btn" disabled={saving} onClick={()=>remove(selected)}>Excluir selecionadas</button></div>}{message&&<div className="form-message error">{message}</div>}
 {edit&&<div className="modal-backdrop"><div className="modal dashboard-modal"><div className="modal-head"><div><p className="eyebrow">Movimentação</p><h2>Editar lançamento</h2></div><button className="icon-btn" onClick={()=>setEdit(null)}>×</button></div><div className="form-grid"><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Tipo<select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="debit">Despesa</option><option value="credit">Receita</option></select></label><label className="full">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Valor<input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Conta / Cartão<select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">Sem referência</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.institution_id||'Instituição'} · {a.masked_identifier||a.account_type}</option>)}</select></label><label className="full">Categoria<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Não categorizado</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="modal-actions"><button className="secondary-btn" onClick={()=>setEdit(null)}>Cancelar</button><button className="primary-btn" disabled={saving} onClick={saveEdit}>{saving?'Salvando...':'Salvar alteração'}</button></div></div></div>}
 {category&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">Classificação</p><h2>Editar categoria</h2></div><button className="icon-btn" onClick={()=>setCategory(null)}>×</button></div><label>Categoria<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Não categorizado</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="modal-actions"><button className="secondary-btn" onClick={()=>setCategory(null)}>Cancelar</button><button className="primary-btn" disabled={saving} onClick={saveCategory}>{saving?'Salvando...':'Salvar categoria'}</button></div></div></div>}
 </div>
}
