import Link from 'next/link'
import ClientProfileActions from './ClientProfileActions'
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const fee=(v:number|null,t:string|null)=>v==null?'—':t==='percentage'?`${v}% do patrimônio`:brl.format(v)
export default function ClientProfileView({client:c,family,alerts,accounts,docs,reviews}:{client:any;family:any[];alerts:any[];accounts:any[];docs:any[];reviews:any[]}){return <main className="content client-page"><div className="detail-top"><div><Link href="/clientes" className="back">← Clientes</Link><p className="eyebrow">Dossiê do cliente</p><h1>{c.full_name}</h1><p className="client-code">{c.client_code||'Sem código'}</p></div><div className="profile-actions"><Link className="secondary-btn" href={`/clientes/${c.id}/acessar`}>Acessar Cliente ↗</Link><ClientProfileActions clientId={c.id} initialStatus={c.contract_status}/></div></div>
<section className="profile-section"><div className="section-title"><b>01</b><div><h2>CADASTRO</h2><p>Informações cadastrais e estrutura familiar.</p></div></div><div className="profile-grid">{[['Nome completo',c.full_name],['CPF',c.cpf_cnpj],['E-mail',c.email],['Telefone',c.phone],['Nascimento',c.birth_date?new Date(c.birth_date).toLocaleDateString('pt-BR'):null],['Endereço',[c.address,c.neighborhood,c.city,c.state].filter(Boolean).join(', ')],['Fee',fee(c.fee_value,c.fee_type)],['Status',c.status==='active'?'Ativo':c.status]].map(([k,v])=><div key={k as string}><small>{k}</small><strong>{v||'—'}</strong></div>)}</div>{family.length>0&&<div className="family-list"><h3>Família</h3>{family.map(f=><div className="family-item" key={f.id}><strong>{f.full_name}</strong><span>{f.relationship} · {f.email||'sem e-mail'} · {f.phone||'sem telefone'}</span></div>)}</div>}</section>
<section className="profile-section"><div className="section-title"><b>02</b><div><h2>ONBOARDING</h2><p>Contrato, Suitability e IPS.</p></div></div><div className="onboarding-grid"><div className="onboarding-card"><div className="step-head"><span>Contrato</span><b className="onboarding-status">{c.contract_status==='signed'?'Assinado':c.contract_status==='awaiting_signature'?'Aguardando assinatura':'Pendente'}</b></div><p>Contrato preenchido com os dados cadastrais.</p></div><div className="onboarding-card"><div className="step-head"><span>Suitability</span><b className="onboarding-status">{c.suitability_status==='completed'?c.suitability_profile:'Pendente'}</b></div><p>Classificação Conservador, Moderado ou Arrojado.</p><button className="secondary-btn" disabled>Enviar Suitability</button></div><div className="onboarding-card"><div className="step-head"><span>IPS</span><b className="onboarding-status">{c.ips_status==='completed'?'Concluído':'Pendente'}</b></div><p>Política individual de investimentos.</p><button className="secondary-btn" disabled>Estruturar IPS</button></div></div></section>
<section className="profile-section"><div className="section-title"><b>03</b><div><h2>CRM</h2><p>Relacionamento e alertas.</p></div></div><div className="crm-grid"><div className="crm-card"><small>Última reunião</small><strong>{c.last_meeting_at?new Date(c.last_meeting_at).toLocaleString('pt-BR'):'Ainda não registrada'}</strong><span>Google Calendar será integrado aqui.</span></div><div className="crm-card"><small>Avisos</small><strong>{alerts.length} aberto(s)</strong>{alerts.length?<ul>{alerts.map(x=><li key={x.id}>{x.title}</li>)}</ul>:<span>Nenhum lembrete pendente.</span>}</div><div className="crm-card"><small>Revisões</small><strong>{reviews.length}</strong><span>{reviews.length?'Há itens aguardando validação.':'Nenhuma pendência.'}</span></div></div></section>
<section className="profile-section"><div className="section-title"><b>04</b><div><h2>CONTAS E DOCUMENTOS</h2><p>Base operacional do cliente.</p></div></div><div className="content-grid"><div className="panel"><div className="panel-head"><h2>Contas</h2><span className="counter">{accounts.length}</span></div>{accounts.length?<div className="client-grid">{accounts.map(x=><div className="client-card" key={x.id}><div className="client-avatar">{(x.institution_id||'B')[0]}</div><div><strong>{x.institution_id||'Instituição'}</strong><span>{x.account_type} · {x.masked_identifier||'protegido'}</span></div></div>)}</div>:<div className="empty">Nenhuma conta conectada.</div>}</div><div className="panel"><div className="panel-head"><h2>Documentos</h2><span className="counter">{docs.length}</span></div>{docs.length?<div className="review-list">{docs.map(d=><div className="review-item" key={d.id}><div><strong>{d.file_name}</strong><small>{d.document_type} · {d.processing_status}</small></div></div>)}</div>:<div className="empty">Nenhum documento importado.</div>}</div></div></section><Link href={`/clientes/${c.id}/acessar`} className="client-access-bar">Acessar Cliente <span>Visualizar a experiência completa →</span></Link></main>}
