import Link from 'next/link'
import {createClient} from '@/lib/supabase/server'
import {redirect} from 'next/navigation'
import AdminSidebar from './AdminSidebar'
import DashboardActions from './DashboardActions'
import OpenPdfButton from './OpenPdfButton'

const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
export default async function HomePage(){
 const s=await createClient();const {data:a}=await s.auth.getClaims();if(!a?.claims?.sub)redirect('/login')
 const {data:access}=await s.rpc('get_my_access');const u=access?.[0];if(!u?.is_active||String(u.role).toLowerCase()!=='admin')redirect('/login?error=unauthorized')
 const [{data:user},{data:clients},{data:docs},{data:reviews},{data:tx},{data:summary}]=await Promise.all([
  s.from('users').select('full_name').eq('id',a.claims.sub).maybeSingle(),
  s.from('clients').select('id,full_name,preferred_name,status,updated_at').eq('status','active').order('updated_at',{ascending:false}),
  s.from('documents').select('id,file_name,processing_status,data_integrity_status,uploaded_at').order('uploaded_at',{ascending:false}).limit(6),
  s.from('reviews').select('id,reason,severity,created_at').eq('status','open').order('created_at',{ascending:false}).limit(6),
  s.from('transactions').select('id,transaction_date,description_original,amount,direction,category_id,institution_id').eq('is_active',true).order('transaction_date',{ascending:false}).limit(6),
  s.from('vw_monthly_financial_summary').select('month,total_income,total_expenses,savings_capacity').order('month',{ascending:false}).limit(1)
 ])
 const latest=summary?.[0];const income=Number(latest?.total_income??0);const expenses=Number(latest?.total_expenses??0);const savings=Number(latest?.savings_capacity??0)
 return <main className="app-shell"><AdminSidebar userName={user?.full_name||'Admin'}/><section className="content"><header className="topbar"><div><p className="eyebrow">Workspace · Administração</p><h1>Visão geral</h1><p className="muted">Uma visão rápida da operação, dos clientes e da qualidade da base.</p></div><div className="topbar-actions"><Link className="secondary-btn" href="/clientes">Clientes</Link><Link className="secondary-btn" href="/gestao-financeira">Gestão Financeira</Link><DashboardActions clients={clients??[]}/></div></header>
 <section className="period-bar"><div><span>Último período disponível</span><strong>{latest?new Date(latest.month as string).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):'Sem dados'}</strong></div><div className="period-summary"><span>Base operacional</span><strong>{clients?.length||0} clientes ativos</strong></div></section>
 <section className="metrics"><div className="metric-card accent"><span>Clientes ativos</span><strong>{clients?.length||0}</strong><small>base atendida</small></div><div className="metric-card"><span>Documentos recentes</span><strong>{docs?.length||0}</strong><small>últimos documentos</small></div><div className="metric-card"><span>Revisões abertas</span><strong>{reviews?.length||0}</strong><small>{reviews?.length?'itens para validação':'base limpa'}</small></div><div className="metric-card"><span>Capacidade de poupança</span><strong className={savings>=0?'positive':'negative'}>{brl.format(savings)}</strong><small>{income>0?`${(savings/income*100).toFixed(1)}% da receita`: 'sem histórico'}</small></div></section>
 <section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h2>Resumo financeiro</h2><p className="muted">Indicadores do último período disponível.</p></div><Link className="text-btn" href="/gestao-financeira">Abrir gestão financeira →</Link></div><div className="settings-grid" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}><div><span>Receitas</span><strong>{brl.format(income)}</strong></div><div><span>Despesas</span><strong>{brl.format(expenses)}</strong></div><div><span>Poupança</span><strong className={savings>=0?'positive':'negative'}>{brl.format(savings)}</strong></div></div></div><div className="panel insight-panel"><div className="panel-head"><div><h2>Próximos passos</h2><p className="muted">A operação que merece atenção agora.</p></div><span className="spark">✦</span></div><div className="insight"><span>01</span><div><strong>{clients?.length?'Gerencie sua base de clientes':'Cadastre o primeiro cliente'}</strong><p>{clients?.length?'Acesse Clientes para abrir cadastros e onboarding.':'Crie um cliente para liberar documentos e gestão financeira.'}</p></div></div><div className="insight"><span>02</span><div><strong>Importe documentos</strong><p>Use PDF de extratos para alimentar a base financeira.</p></div></div></div></section>
 <section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Clientes recentes</h2><p className="muted">Acesso rápido aos dossiês.</p></div><Link className="text-btn" href="/clientes">Ver todos →</Link></div>{clients?.length?<div className="client-grid">{clients.slice(0,6).map(c=><Link className="client-card" href={`/clientes/${c.id}`} key={c.id}><div className="client-avatar">{initials(c.full_name)}</div><div><strong>{c.preferred_name||c.full_name}</strong><span>Ativo</span></div><b>›</b></Link>)}</div>:<div className="empty"><strong>Você não tem clientes ativos no momento.</strong><span>Adicione seu primeiro cliente para começar.</span><Link className="primary-btn" href="/clientes">Adicionar cliente</Link></div>}</div><div className="panel"><div className="panel-head"><div><h2>Central de revisão</h2><p className="muted">Itens que precisam de validação.</p></div><span className="counter">{reviews?.length||0}</span></div>{reviews?.length?<div className="review-list">{reviews.map(r=><div className="review-item" key={r.id}><span className={`severity ${r.severity}`}>{r.severity}</span><div><strong>{r.reason}</strong><small>{new Date(r.created_at).toLocaleString('pt-BR')}</small></div></div>)}</div>:<div className="empty"><div className="empty-icon">✓</div><strong>Base limpa</strong><span>Nenhuma revisão aberta no momento.</span></div>}</div></section>
 <section className="panel" id="documentos"><div className="panel-head"><div><h2>Documentos recentes</h2><p className="muted">Parsing, integridade e origem dos dados.</p></div><OpenPdfButton/></div><div className="table-wrap"><table><thead><tr><th>Documento</th><th>Processamento</th><th>Integridade</th></tr></thead><tbody>{docs?.map(d=><tr key={d.id}><td><strong>{d.file_name||'Documento'}</strong><small>{new Date(d.uploaded_at).toLocaleString('pt-BR')}</small></td><td><span className={`pill ${d.processing_status}`}>{d.processing_status}</span></td><td><span className={`pill ${d.data_integrity_status}`}>{d.data_integrity_status}</span></td></tr>)}{!docs?.length&&<tr><td colSpan={3} className="table-empty">Nenhum documento importado.</td></tr>}</tbody></table></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Movimentações recentes</h2><p className="muted">Últimos lançamentos ingeridos pelo sistema.</p></div><Link className="text-btn" href="/gestao-financeira">Ver todas →</Link></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Instituição</th><th>Valor</th></tr></thead><tbody>{tx?.map(t=><tr key={t.id}><td>{new Date(t.transaction_date).toLocaleDateString('pt-BR')}</td><td>{t.description_original}</td><td>{t.institution_id||'—'}</td><td className={t.direction==='credit'?'positive':'negative'}>{t.direction==='credit'?'+':'-'}{brl.format(Number(t.amount))}</td></tr>)}{!tx?.length&&<tr><td colSpan={4} className="table-empty">Nenhuma movimentação encontrada.</td></tr>}</tbody></table></div></section>
 </section></main>
}
