import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import ClientActions from '../ClientActions'
import ClientFinancialFilters from '../ClientFinancialFilters'
import ClientTransactions from '../ClientTransactions'
import ClientPageStyles from '../../ClientPageStyles'
import ClientFinancialStyles from '../ClientFinancialStyles'
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
export default async function ClientAccess({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params,q=await searchParams,s=await createClient();const {data:a}=await s.auth.getClaims();if(!a?.claims?.sub)redirect('/login')
 const {data:c}=await s.from('clients').select('id,full_name,client_code').eq('id',id).maybeSingle();if(!c)notFound()
 const [{data:tx},{data:cats},{data:accounts},{data:targets}]=await Promise.all([
  s.from('transactions').select('id,transaction_date,description_original,amount,direction,category_id,account_id,is_transfer,is_investment_flow,is_card_payment,expense_nature').eq('client_id',id).eq('is_active',true).order('transaction_date',{ascending:false}).limit(1000),
  s.from('categories').select('id,name,icon').eq('active',true).order('name'),
  s.from('accounts').select('id,institution_id,account_type,masked_identifier').eq('client_id',id),
  s.from('client_category_targets').select('category_id,target_amount').eq('client_id',id).eq('active',true)
 ])
 let rows=tx??[]
 const dateMatch=(d:string)=>{const mode=q.date_mode||'range',v=q.from||'';if(!v)return true;if(mode==='year')return d.startsWith(v);if(mode==='month'){const [m,y]=v.split('/');return d.startsWith(`${y}-${m}`)}return (!q.from||d>=q.from)&&(!q.to||d<=q.to)}
 rows=rows.filter(t=>dateMatch(t.transaction_date)&&(!q.description||t.description_original.toLowerCase().includes(q.description.toLowerCase()))&&(!q.category||t.category_id===q.category)&&(!q.institution||t.account_id===q.institution)&&(!q.min||Number(t.amount)>=Number(q.min.replace(',','.')))&&(!q.max||Number(t.amount)<=Number(q.max.replace(',','.'))))
 const expenses=rows.filter(t=>t.direction==='debit'&&!t.is_transfer&&!t.is_investment_flow&&!t.is_card_payment),income=rows.filter(t=>t.direction==='credit'&&!t.is_transfer&&!t.is_investment_flow),sum=(arr:any[])=>arr.reduce((n,t)=>n+Number(t.amount),0),inc=sum(income),exp=sum(expenses),save=inc-exp
 const groups=new Map<string,number>();expenses.forEach(t=>groups.set(t.category_id||'none',(groups.get(t.category_id||'none')||0)+Number(t.amount)));const targetMap=new Map((targets??[]).map(t=>[t.category_id,Number(t.target_amount)]))
 const top=[...groups.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">C</div><div><strong>Campos</strong><span>Wealth OS</span></div></div><div className="workspace-label">CLIENTE</div><nav className="nav"><Link className="nav-item" href={`/clientes/${id}`}>← Voltar <span>Admin</span></Link><a className="nav-item active" href="#financeiro">Gestão Financeira <span>↗</span></a></nav><div className="sidebar-footer"><div className="avatar">{c.full_name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{c.full_name}</strong><span>{c.client_code||'Cliente'}</span></div></div></aside><section className="content"><ClientPageStyles/><ClientFinancialStyles/>
 <header className="topbar"><div><p className="eyebrow">Modo Cliente</p><h1>{c.full_name}</h1><p className="client-code">{c.client_code||'Sem código'}</p></div><div className="topbar-actions"><ClientFinancialFilters categories={cats??[]} accounts={accounts??[]}/><ClientActions clientId={id}/></div></header>
 <section className="metrics"><div className="metric-card accent"><span>Receitas</span><strong>{brl.format(inc)}</strong><small>período filtrado</small></div><div className="metric-card"><span>Despesas</span><strong>{brl.format(exp)}</strong><small>período filtrado</small></div><div className="metric-card"><span>Capacidade de Poupança</span><strong className={save>=0?'positive':'negative'}>{brl.format(save)}</strong><small>receitas menos despesas</small></div><div className="metric-card"><span>Meta vs Realizado</span><strong>{top.length?`${Math.round(top.reduce((n,[id,v])=>n+(targetMap.get(id)?v/targetMap.get(id)!*100:0),0)/(top.filter(([id])=>targetMap.has(id)).length||1))}%`:'—'}</strong><small>média das metas com configuração</small></div></section>
 <section className="dashboard-grid" id="financeiro"><div className="panel chart-panel"><div className="panel-head"><div><h2>Evolução de despesas x receitas</h2><p className="muted">A evolução seguirá o mesmo conjunto filtrado.</p></div></div><div className="chart-empty">Os dados históricos serão visualizados aqui à medida que o período e as movimentações forem consolidados.</div></div><div className="panel insight-panel"><div className="panel-head"><div><h2>Insights</h2><p className="muted">Leitura automática do período.</p></div><span className="spark">✦</span></div><div className="insight"><span>01</span><div><strong>Capacidade de poupança</strong><p>{inc?`${(save/inc*100).toFixed(1)}% da receita ficou disponível após as despesas consideradas.`:'Sem receitas no período.'}</p></div></div><div className="insight"><span>02</span><div><strong>Maior categoria</strong><p>{top.length?cats?.find(x=>x.id===top[0][0])?.name||'Não categorizado':'Sem despesas classificadas.'}</p></div></div></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Principais categorias</h2><p className="muted">Categorias que apresentaram movimentação no período.</p></div></div>{top.length?<div className="category-list">{top.map(([id,value])=>{const target=targetMap.get(id)||0,pct=target?value/target*100:0;return <div className="category-row" key={id}><div className="category-icon">{cats?.find(x=>x.id===id)?.icon||'◌'}</div><div className="category-main"><div><strong>{cats?.find(x=>x.id===id)?.name||'Não categorizado'}</strong><span>{brl.format(value)}</span></div><div className="progress"><i style={{width:`${Math.min(pct,100)}%`}}/></div><small>{target?`${pct.toFixed(0)}% da meta · ${brl.format(target)} meta`:'Meta não definida'}</small></div></div>})}</div>:<div className="empty">Nenhuma despesa no período selecionado.</div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Consolidado</h2><p className="muted">Realizado x meta por categoria. Clique na categoria para filtrar as movimentações.</p></div></div><div className="table-wrap"><table><thead><tr><th>Categoria</th><th>Realizado</th><th>Meta</th><th>Meta atingida</th></tr></thead><tbody>{[...groups.entries()].sort((a,b)=>b[1]-a[1]).map(([id,value])=>{const target=targetMap.get(id)||0,pct=target?value/target*100:0;const params=new URLSearchParams(Object.entries(q).filter(([,v])=>v).map(([k,v])=>[k,v]));params.set('category',id);return <tr key={id}><td><Link href={`?${params.toString()}#movimentacoes`}>{cats?.find(x=>x.id===id)?.name||'Não categorizado'}</Link></td><td>{brl.format(value)}</td><td>{target?brl.format(target):'—'}</td><td><div className="progress"><i style={{width:`${Math.min(pct,100)}%`}}/></div><small>{target?`${pct.toFixed(0)}%`:'Sem meta'}</small></td></tr>})}</tbody></table></div></section>
 <section className="panel" id="movimentacoes"><div className="panel-head"><div><h2>Movimentações consideradas</h2><p className="muted">Detalhe das movimentações que alimentam os indicadores e o consolidado.</p></div></div><ClientTransactions clientId={id} rows={rows.map(t=>({id:t.id,transaction_date:t.transaction_date,description_original:t.description_original,amount:Number(t.amount),direction:t.direction,category_id:t.category_id,account_id:t.account_id}))} categories={cats??[]} accounts={accounts??[]}/></section>
 </section></main>
}
